### ISSUE TITLE
UserInfo 관련

### ISSUE THREAD

**Issue by Rojojun** [Geupjo-Hackathon/KoreanTiger-FE#3]
usePathname 훅 받아서 '/student', '/teacher'로 분기 처리 하였습니다.

API통신 때 useStatus로 (단발성이기 때문에 귀찮아서 훅관리 하기 싫어서... status로 ㅋㅋ) 해서 한 번에 객체 얻어 오는게 어떨까용~?!!?

**Comment by SeryeongK** [comment]
넵 usePathname 처리 확인했습니다.
좋습니다! useState 말씀하는 거 맞으신가요?

**Comment by Rojojun** [comment]
앗 넵 졸면서 써서 ㅋㅋㅋ 넵 state로 다 처리하려고 합니다!!
